// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhX1QqYwS0eGfep8PIVasEyiySloTB2Aw',
    appId: '1:731614538303:web:9b043ca155b4a50174268a',
    messagingSenderId: '731614538303',
    projectId: 'recetapp-9c1bf',
    authDomain: 'recetapp-9c1bf.firebaseapp.com',
    storageBucket: 'recetapp-9c1bf.firebasestorage.app',
    measurementId: 'G-85QKPBWTM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_HxrhiFCzHchyydCGTj0L7B9YTZcY_Y',
    appId: '1:731614538303:android:a790e80c9eebf3aa74268a',
    messagingSenderId: '731614538303',
    projectId: 'recetapp-9c1bf',
    storageBucket: 'recetapp-9c1bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-W0E1e8alvHgbGbzM4ocDUInLTC02qc',
    appId: '1:731614538303:ios:6cf21a85cdfcee3874268a',
    messagingSenderId: '731614538303',
    projectId: 'recetapp-9c1bf',
    storageBucket: 'recetapp-9c1bf.firebasestorage.app',
    iosBundleId: 'com.aob.recetapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-W0E1e8alvHgbGbzM4ocDUInLTC02qc',
    appId: '1:731614538303:ios:6cf21a85cdfcee3874268a',
    messagingSenderId: '731614538303',
    projectId: 'recetapp-9c1bf',
    storageBucket: 'recetapp-9c1bf.firebasestorage.app',
    iosBundleId: 'com.aob.recetapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhX1QqYwS0eGfep8PIVasEyiySloTB2Aw',
    appId: '1:731614538303:web:69472d7f20a6fc3174268a',
    messagingSenderId: '731614538303',
    projectId: 'recetapp-9c1bf',
    authDomain: 'recetapp-9c1bf.firebaseapp.com',
    storageBucket: 'recetapp-9c1bf.firebasestorage.app',
    measurementId: 'G-N11YSEDQD1',
  );
}
